### ISSUE TITLE
TODO 0.5

### ISSUE THREAD

**Issue by yann300** [ethereum/browser-solidity#669]
Here are the minimal stuff we need to address before going back to normal with the build ( deploy to remix.ethereum.org ) . Then I think it would be good to add versioning ( => 0.5) .
The list is not fixed and we can still add new item if needed.

 - [x] Terminal https://github.com/ethereum/browser-solidity/issues/657
 - [x] UI Terminal / Transaction log https://github.com/ethereum/browser-solidity/issues/675
 - [x] browser testing for the Terminal https://github.com/ethereum/browser-solidity/pull/732
 - [x] Log transactions from txListener
 - [x] Ability to start debugging transaction from the log
 - [x] UX - Click on a logged transaction expand it (or open a modal) to display all infos related to the txs
 - [x] Merge the Best Practice PR. https://github.com/ethereum/browser-solidity/pull/654
 - [x] Merge the Support tab. https://github.com/ethereum/browser-solidity/pull/647
 - [x] Replace the prompt, confirm by modalConfirm, modalPrompt
 - [x] Documentation
 - [x] Important bug fixes ...
 - [x] Remove file tabs and add action in the filepanel https://github.com/ethereum/browser-solidity/issues/677
 - [x] Uses web3 from the Terminal
 - [x] Make Buttons consistent https://github.com/ethereum/browser-solidity/issues/676
 - [x] UI - Modal dilalog that display transaction details. (Issue details https://github.com/ethereum/browser-solidity/issues/674)
 - [x] Alert/Warn when user create a new tx (issue https://github.com/ethereum/browser-solidity/issues/747)

**Comment by serapath** [comment]
> **chris:** wonderful!
some comments: Please re-add line-wrapping for the details. Especially the assembly has to be readable.
can we change "start to compile" to "compiling" while it is compiling?
or call th ebutton "compile" and grey it out while we are compiling
on the run tab there are a little too many borders for my taste

**Comment by serapath** [comment]
I like the list above as a nice overview.

@yann300 
1. I don't exactly know what "back to normal" means, but I would enjoy if there was **always** a "top level issue" (maybe called `Release Candidate v.X.Y.Z`) which has a list of features that need to be implemented before we release the next version of remix or browser-solidity to be used by users.

2. I very very much like, that some of the checkboxes have **issue number links** attached and think all of the todo items should have it to cover the "feature areas" (hopefully each of them an independent module)

3. A linked issue like for example the terminal above https://github.com/ethereum/browser-solidity/issues/657 is again structured in a similar way.


### That way, I can always:
* check the release candidate issue to get an overview
* browse/dig down into the work areas assigned to me to see what to do next
* have a very nice overview and agenda to discuss **and update/restructure** during our weekly meetings

After every weekly online meeting (in order also to not get lost in discussion) - we end up with an up2date issue tree where everyone has certain items assigned so we can work on during the week until the next meeting.

So this part I could imagine starting right now even before we go back to normal.
**And our online meetings probably should always start by everyone opening the current `Release Candidate vX.Y.Z` issue before we even talk anything.**
Then we together do an **"issue tree walk"** - where on each issue, we update/restructure it if necessary and people who worked on an issue say:
1. what they did on it
2. what is the current status and if there are any current problems/blockers
3. what are the next steps :-)

**Comment by ninabreznik** [comment]
That's nice. It would help me too, I think. I otherwise always go into my working time logs and check what I was doing that week :) I wonder how could we also add the timeline overview so that I can for example easily see what I was working on in a certain week...

**Comment by yann300** [comment]
done!
